using System;
using System.Collections.Generic;
using System.Text;

namespace PeerToPeerLib
{
    public class FileEndPoint
    {
        private string _ipAddress;
        public string IpAddress { get; set; }

        private int _portNo;
        public int PortNo { get; set; }

        // IP Address + Filename
        private Dictionary<string, string> _filesInEndPoint;

        public Dictionary<string, string> FilesInEndPoint
        {
            get => _filesInEndPoint;
            set => _filesInEndPoint = value;
        }


        public FileEndPoint()
        {
            
        }

        public FileEndPoint(string ip, int portNo)
        {
            IpAddress = ip;
            PortNo = portNo;
            FilesInEndPoint = new Dictionary<string, string>();
        }

        public FileEndPoint(string ip, int portNo, bool hasAutoGeneratedFileNames)
        {
            IpAddress = ip;
            PortNo = portNo;
            FilesInEndPoint = new Dictionary<string, string>()
            {
                {"aFile", IpAddress },
                {"fancyFile", IpAddress }
            };
        }
        
    }
}
